Cookbook advanced use
RMI-PACTA/workflow.multi.loanbook pull request #191
Opened 2024-11-02 16:35 UTC by jacobvjk

wip

2024-11-05 13:05 UTC, jdhoffa requested changes
First batch of comments

2024-11-05 13:05 UTC, jdhoffa commented on vignettes/cookbook.Rmd
> +This section provides a ore detailed look at some of the more advanced use cases of the `pacta.multi.loanbook` package for PACTA for Supervisors analysis. First, we will touch on the technical side o
```suggestion
This section provides a more detailed look at some of the more advanced use cases of the `pacta.multi.loanbook` package for PACTA for Supervisors analysis. First, we will touch on the technical side of adjusting the analysis to your needs. Then, we will look at some research questions that may occur in the field of banking supervision with regard to climate transition risk and how the `pacta.multi.loanbook` package can help answer them.
```

2024-11-05 13:05 UTC, jdhoffa commented on vignettes/cookbook.Rmd
> +**Method:** By analyzing different types of banks (e.g., systemically important banks, credit unions, specialized banks - lending to specific sectors, or banks with public commitments (e.g., targets,
This seems to have a double open bracket... not sure the best way to adjust.
"By analyzing different types of banks (e.g., systemically important banks, credit unions, specialized banks - lending to specific sectors, or banks with public commitments (e.g., targets, ..."

2024-11-05 13:05 UTC, jdhoffa commented on vignettes/cookbook.Rmd
> +- Do we have any groups (aggregate or bank type level) what have significantly lower match success rates than other groups? If so, it may be difficult to draw conclusions about that group and it may
```suggestion
- Do we have any groups (aggregate or bank type level) that have significantly lower match success rates than other groups? If so, it may be difficult to draw conclusions about that group and it may be a good idea to review the options for increasing the match success rate. You can use the charts in `../prioritized_loanbooks_and_diagnostics_\*/plot_match_success_rate_rel_*.png` to identify groups with low match success rates. Alternatively you can use the file `../prioritized_loanbooks_and_diagnostics_\*/lbk_match_success_rate_*.csv` for the precise numbers.
```

2024-11-05 13:27 UTC, jacobvjk commented on vignettes/cookbook.Rmd
> +**Method:** By analyzing different types of banks (e.g., systemically important banks, credit unions, specialized banks - lending to specific sectors, or banks with public commitments (e.g., targets,
addressed

2024-11-05 14:06 UTC, cjyetman approved these changes

2024-11-06 08:14 UTC, jdhoffa approved these changes

2024-11-06 08:14 UTC, jdhoffa commented
Approved syntactically, pending a more in-depth review of the cookbook overall

2024-11-06 08:17 UTC, merged